### ISSUE TITLE
Remove nested subscription attributes from User

### ISSUE THREAD

**Issue by aldesantis** [solidusio-contrib/solidus_subscriptions#124]
Currently, the `Spree::User` model (or whatever `Spree.user_class` is) [is decorated](https://github.com/solidusio-contrib/solidus_subscriptions/blob/master/app/decorators/models/solidus_subscriptions/spree/user/have_many_subscriptions.rb) not only to add a `has_many :subscriptions` association, but also to add an `accepts_nested_attributes_for :subscriptions` statement.

This seems like a terrible idea and it creates a lot of indirection and uncertainty around the correct way to generate a subscription for a user. It would be better to remove this functionality altogether and rely on the specific API controllers instead.

**Comment by luca-landa** [comment]
@aldesantis just to be sure, is it correct to say that every CRUD action that is currently possible through `accepts_nested_attributes_for :subscriptions`, can already be done in other ways? Or am I missing something?

If that is the case, what do you think about just deprecating the feature right now?

**Comment by ChristianRimondi** [comment]
Closed by #193
