### ISSUE TITLE
Subscription processing failing repeatedly

### ISSUE THREAD

**Issue by dhemmat** [solidusio-contrib/solidus_subscriptions#13]
Certain subscriptions are being processed repeatedly. It seems that the payment is failing (denied by the gateway), triggering the `FailureDispatcher#dispatch` method, which contains a call to `order.cancel!`

I'm not sure why but some orders already appear to be cancelled before they get here, producing the following error: 

```
Cannot transition state via :cancel from :canceled (Reason(s): State cannot transition via "cancel")
/home/deploy/.bundler/goby/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/event.rb:224:in `block in add_actions'
/home/deploy/.bundler/goby/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/machine.rb:725:in `block (2 levels) in define_helper'
/home/deploy/.bundler/goby/ruby/2.3.0/bundler/gems/solidus_subscriptions-c362bf90ea0a/app/models/solidus_subscriptions/failure_dispatcher.rb:7:in `dispatch'
```
This causes the job to fail and enter the retry queue, this cycle is repeated until the max failed attempts number is hit. 

Maybe we can change `order.cancel!` to `order.cancel` to make it fail silently? I haven't identified why these orders are reaching the failure dispatcher with a canceled state.

**Comment by brendandeere** [comment]
@dhemmat 

Thanks for bringing this to my attention. I will look into this. In the mean time if you are able to provide steps in a sample store to reproduce this bug, it would help me identify the root cause.
