### ISSUE TITLE
Solidus Subscriptions incompatible with solidus 2.3

### ISSUE THREAD

**Issue by joeljackson** [solidusio-contrib/solidus_subscriptions#14]
Solidus 5.3 depends on rails 5.1 which requires some changes to the migrations and "before_filter"

**Comment by jhawthorn** [comment]
Hi @joeljackson, Solidus 2.3 is bleeding edge and we only added support for Rails 5.1 yesterday so it will take some time for our extensions to catch up.

I've started the work in #16, but it is incomplete.

**Comment by brendandeere** [comment]
Fixed in #16
