### ISSUE TITLE
Simplify subscription processing logic

### ISSUE THREAD

**Issue by aldesantis** [solidusio-contrib/solidus_subscriptions#170]
Currently, `SolidusSubscriptions::Processor` is a bit too clever in how it tries to group subscriptions/installments together. As a result, it's very complicated and it generates background jobs that doo too much stuff, trying to process multiple installments at the same time.

We should streamline both the processor and the background job that fulfills subscriptions by distributing the workload horizontally as much as possible, which should also improve performance.

**Comment by ChristianRimondi** [comment]
Closed by #172
