### ISSUE TITLE
Introduce semantic versioning and releases

### ISSUE THREAD

**Issue by dhemmat** [solidusio-contrib/solidus_subscriptions#19]
Can we introduce proper semantic versioning? it seems that this gem is stuck at 0.0.1, but going through the commit history I see a number of patches, backwards compatible changes and backwards incompatible changes. We would love to take advantage of the new changes but can't until the versions change.

**Comment by dhemmat** [comment]
@brendandeere, any thoughts on this?

**Comment by brendandeere** [comment]
Thanks for you input. 

Providing support for a smooth upgrade path is definitely something I would like to provide. The next official planned release will be the 1.0.0 (conforming to Semver). Once the gem is green with solidus master again and the known issues with the adminitrative portal are fixed.

**Comment by dhemmat** [comment]
@brendandeere any update on when 1.0.0  might be released?
