### ISSUE TITLE
Fix sandbox generation

### ISSUE THREAD

**Issue by luca-landa** [solidusio-contrib/solidus_subscriptions#196]
After creating a sandbox, the store is not mounted in `config.rb` and the migrations aren't copied and executed entirely.

There's this error in the process: `Could not find generator 'spree:install'`.

Currently, the Solidus sandbox generation is working, so it may be a problem with a specific dependency of this gem.

**Comment by blocknotes** [comment]
I'm doing some investigations here.
- I tried to move back to a commit of 1 month ago to check if we have a regression, but the problem looks the same - so It could be related to something wrong with an external dependency;
- after cloning the repo and running `bin/rails-sandbox` at some point I see a `Could not find generator 'spree:install'.`:
```shell
Dropped database 'db/development.sqlite3'
Database 'db/test.sqlite3' does not exist
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'
Could not find generator 'spree:install'.
Run `bin/rails generate --help` for more options.
      create  config/initializers/devise.rb
         run  bundle exec rake railties:install:migrations FROM=solidus_auth from "."
```

**Comment by blocknotes** [comment]
It looks like that the issue is related to the change from `spree:install` to `solidus:install` (https://github.com/solidusio/solidus/pull/3538) - but I'm still tracking down better what happened here.

**Comment by blocknotes** [comment]
`solidus:install` should be available with the next release of `solidus_dev_support`.
When this happens we will need to run `solidus extension .` to apply the change to our `bin/sandbox`
