### ISSUE TITLE
Improve description for promotion rules

### ISSUE THREAD

**Issue by seand7565** [solidusio-contrib/solidus_subscriptions#205]
> I think you used the “Subscription promotion rule” instead of “Subscription order promotion rule”. I know this is super-confusing, but the first one is applied to the order that generates a subscription (i.e. a customer’s first order when they sign up to the PP), while the second is applied to all orders in a subscription.

X-posting from Slack, but that's basically the gist of it. We might want to add some descriptive text/comments to the rule file, the readme, and the rule partial (so non-coder admin can understand the difference too)

**Comment by luca-landa** [comment]
Is it a possibility to change the rules name right now? If so, what about "Subscription creation order promotion rule" and "Subscription installment order promotion rule" ?

**Comment by aldesantis** [comment]
@luca-landa yep, we should be able to change them.

**Comment by luca-landa** [comment]
@aldesantis if somebody is using the extension now, their subscriptions processing will break after renaming the promotion rules classes. How should we handle this? Should we provide a script to fix the names in the database or is it just too much worry because we aren't at `1.0.0` yet?

**Comment by aldesantis** [comment]
@luca-landa I think we should make a PR for adding a migration for the promotion rule names too 🙂 Nonetheless, this is still a breaking change because someone might be relying on those class names, so I'm adding a "breaking" label.

**Comment by luca-landa** [comment]
@aldesantis created it #216, let me know if everything is okay with this
