### ISSUE TITLE
Why do we remove :subscribable_id from the permitted attributes when creating a Subscription?

### ISSUE THREAD

**Issue by cesartalves** [solidusio-contrib/solidus_subscriptions#222]
That is, [here](https://github.com/solidusio-contrib/solidus_subscriptions/blob/d462e8eaaf6481f6e5434de575290442673fc538/app/controllers/solidus_subscriptions/api/v1/subscriptions_controller.rb#L81)

**Comment by aldesantis** [comment]
That is a very good question. 😅

I'm pretty sure it's a bug: originally, we only exposed an API endpoint for updating a subscription, not creating one. When updating, it makes sense that if someone wants to change the subscribable, they need to delete the existing line item and create a new one. This obviously doesn't apply to the creation.

Feel free to submit a PR to fix this!
