### ISSUE TITLE
Method to filter out line_items that are associated with a subscription

### ISSUE THREAD

**Issue by markmead** [solidusio-contrib/solidus_subscriptions#227]
It would be nice to be able to call `order.line_item_products` and `order.line_item_subscriptions` so that we can split the two and also stop the below from happening;

<img width="959" alt="Screenshot 2021-04-27 at 15 54 14" src="https://user-images.githubusercontent.com/50486078/116263418-42df3700-a771-11eb-8d06-ddde3806af37.png">

This is one subscription but the `line_item` is showing above it, it's fine to remove this if you are only doing subscriptions but what about shops that offer both products and subscription purchases?

**Comment by aldesantis** [comment]
That makes sense! Would you like to give it a try? 🙂
