### ISSUE TITLE
I can't get rid of sollidus_subscription

### ISSUE THREAD

**Issue by keferboeck** [solidusio-contrib/solidus_subscriptions#265]
I removed the gem, and reversed the installation. Firstly, the migrations remained, so I had to manually write a migration to get rid of any tables, indexes and foreign keys. Now that the gem is uninstalled and all migrations removed, the entire store broke into pieces, as whatever we do traces of the gem keep appearing - i.e.: 

`ActionView::Template::Error (undefined method 'subscribable' for #<Spree::Variant:0x00007feec5b059d0>):
    106: <div data-hook="admin_product_form_subscribable">
    107:   <%= f.field_container :subscribable do %>
    108:     <label>
    109:       <%= f.check_box :subscribable %>
    110:       <%= Spree::Product.human_attribute_name(:subscribable) %>
    111:     </label>
    112:   <% end %>`

No idea where this is coming from? What do we have to do - step by step to remove the gem?

**Comment by kennyadsl** [comment]
Hey there! Can you please let us know how you solved this if you have time? It could be helpful for the next person with the same issue!

**Comment by keferboeck** [comment]
Hi @kennyadsl, we haven't solved the issue. We are at an early stage of development, so we set up a new shop and moved everything over that was working. We spent two days on the issue above, and it was cheaper to create a new shop simply, and we are now writing our subscription logic, as we can't risk another issue that cannot be solved.

We still have the old shop on our server, so if you want me to troubleshoot - I am happy to assist!

**Comment by kennyadsl** [comment]
Yes please, I'd like to take a look if possible.

**Comment by keferboeck** [comment]
This issue has been resolved - the problem was we have [Solidus User Roles](https://github.com/boomerdigital/solidus_user_roles) added to our Gemfile. Upon installation it populates a permission table (Spree::PermissionSet) and there was the following reference in the table:

```
SubscriptionManagement - SolidusSubscriptions::PermissionSets::SubscriptionManagement
DefaultCustomer - SolidusSubscriptions::PermissionSets::DefaultCustomer
```

Upon deleting all entries that refer to SolidusSubscription the issue above was resolved!
