### ISSUE TITLE
Use custom User class

### ISSUE THREAD

**Issue by yyamanoi1222** [solidusio-contrib/solidus_subscriptions#43]
I want to use custom User class in this Gem. 
So could you replace some files like 
```
Spree::User
```
to

```
Spree.user_class
```

**Comment by brendandeere** [comment]
Hey! good call. This is definitely something I tried to do. But I found at least one place where one slipped through:

https://github.com/solidusio-contrib/solidus_subscriptions/blob/9f3a33f2bc7bf76801fb3e2db68e4b3906647b9c/lib/solidus_subscriptions/processor.rb#L25 

I'll clean that up and any others I find

**Comment by yyamanoi1222** [comment]
Thank you for your answer.
I'm looking forward to update.
