### ISSUE TITLE
Promo codes? 

### ISSUE THREAD

**Issue by brendandeere** [solidusio-contrib/solidus_subscriptions#8]
As a customer, applying a promo code to an order, I want the promotion to apply to my orders fulfilling my subscriptions so that I can continue getting discounts

**Comment by joeljackson** [comment]
How do you envision this happening? Promos apply to orders, and the order is generated at the time of charging.

Potentially generate a temporary order object that is not saved that is used to check the value of the promo?

**Comment by brendandeere** [comment]
@joeljackson 

The subscription gem generates a new `Spree::Order` object to fulfil each Installment of a Subscription.
A first thought at implementing this would be to persist the promotions which are applicable to an order at the time of purchase in a way which would be visible to the `Subscription` object. 
Then apply the same promotions to any order which fulfils a subscription. 

This functionality was suggested by a member of the solidus community who is using their own implementation of subscriptions.

**Comment by joeljackson** [comment]
@brendandeere 

I'd like to be able to give customers an estimate of the cost of their upcoming orders. Seems easy enough with no promos, but when you start talking about promos it seems like it would be nice to use the OrderUpdater to not have to reimplement adjustment functionality.

**Comment by brendandeere** [comment]
@joeljackson 

That is definitely a fair requirement that should be considered if this feature is implement. I definitely would not want to see a re implementation of the adjustment functionality

**Comment by joeljackson** [comment]
What are thoughts on esuring that a promo can apply to an order that does not yet exist?

**Comment by joeljackson** [comment]
Has it ever been considered to generate an order at the same time as the installment? It seems like this would make a few things much simpler because we could reuse the promo application code from core spree as well as the adjustment calculation.
